[features]
seeds = false
skip-lint = false
[programs.localnet]
s_otc = "CDHeGsm3qvtS3R8kWUXg6KYskYYvaoEwjnjH1CYNU9RS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/atahanyild/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
